### ISSUE TITLE
Unable to initialize scran.js, probably missing something!

### ISSUE THREAD

**Issue by rob-p** [kanaverse/scran.js#70]
The simplest possible test program seems to fail for me (both on OS X — and x86 Mac — and on linux).  I tired the script below:

```
import * as scran from "scran.js"
await scran.initialize({ numberOfThreads: 4 })
```

with `package.json`:

```
{
  "type": "module",
  "dependencies": {
    "scran.js": "^2.0.3"
  }
}
```

and on both platforms I get the following (absurdly long) error:

<img width="942" alt="image" src="https://user-images.githubusercontent.com/361470/234960407-7b97658c-d90d-4bbf-ac8c-b1cc00f8c0f0.png">

It looks like it prints line 15 of `scran.js` and then provides the above backtrace.  Any ideas what is going wrong?

Thanks!
Rob

**Comment by LTLA** [comment]
What's your version of Node? On older versions, you'll need a stack of flags; I don't remember them all, but it's something like:

```
    --experimental-wasm-threads
    --experimental-wasm-bulk-memory
    --experimental-wasm-bigint
```

Old Nodes also need:

```
await scran.initialize({ numberOfThreads: 4, localFile: true })
```

because they don't know how to handle `file://` URIs.

Finally, you'll need to add a `await scran.terminate();` if you want the program to actually end, as Node doesn't want to shut down while there's still workers spinning around. This should be fixed in the latest version of Emscripten but we haven't updated to the latest toolchain yet.

So, in total, the following works for me on Node.js v16.19.1:

```js
import * as scran from "scran.js"
await scran.initialize({ numberOfThreads: 4, localFile: true })
await scran.terminate();
```

**Comment by rob-p** [comment]
This is Node 19.02.  Is that too new?

**Comment by jkanche** [comment]
I am on the new version of node (19.6.1) and I had to enable these flags 

```sh
⋊> ~/P/p/k/rob_test node --experimental-wasm-modules --no-experimental-fetch --experimental-wasm-threads --experimental-modules  index.js
```

and my index.js

```js
import * as scran from "scran.js";
await scran.initialize({ numberOfThreads: 4, localFile: true });
console.log("i can load");
await scran.terminate()
```

**Comment by jkanche** [comment]
every time node updates, we need to figure out the new set of flags to enable these cutting edge "experimental" features :)

**Comment by rob-p** [comment]
Hi @jkanche,

  Thanks; it works with the flags you provide! By the way, with Node 19, is there a reason we still need to provide `localFile: true` (it doesn't seem to work without this).

Thanks!
Rob

**Comment by jkanche** [comment]
i believe we still need to have this patch in our code. 

It still seems to be a problem even though emscripten seems to **_fix_** it.  - https://github.com/emscripten-core/emscripten/issues/10434.
