### ISSUE TITLE
Unable to build the project using dockerfile or manually installing Emscripten and CMake

### ISSUE THREAD

**Issue by thilinib** [kanaverse/scran.js#79]
Hi, Thanks for the great work.

I’m trying to build the project locally and run test cases using the docker file in Mac. But gives me an error as following.

```
=> ERROR [ 7/10] RUN npm i --include=dev                                                                                                       0.3s
------
 > [ 7/10] RUN npm i --include=dev:
#0 0.266 /bin/sh: 1: npm: not found
```

Then I added following code to install npm, node in dockerfile

```
# Installing Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs
```

For some reason, it worked only for version 14 but not for 19. 
However I tried to build image with version 14 and then it gives me the following error.

![Screenshot 2023-07-06 at 10 13 15](https://github.com/kanaverse/scran.js/assets/50691634/20a24183-2431-48be-9f42-62cf58ecf514)

I also tried to build by installing  [Emscripten](https://emscripten.org/docs/getting_started/downloads.html) and [CMake](https://cmake.org/download/).  Still giving me errors, not making warm subdirectory.

It looks like build.sh not compatible with mac or any thing wrong with my side?

**Comment by jkanche** [comment]
if you are using node 19, you might need to enable these flags - https://github.com/kanaverse/scran.js/issues/70#issuecomment-1526553133

**Comment by LTLA** [comment]
At least one docker image works, see [here](https://github.com/kanaverse/scran.js/pkgs/container/scran.js%2Fbuilder).

**Comment by thilinib** [comment]
Hi, 
Thanks for the guidance. The error was with Cmake version with mac os in dockerfile. I again rebuild with installing emscripton and relevant Cmake version manually (without using docker)and it built both node and browser compatible versions.

**Comment by LTLA** [comment]
FYI moved the docker image [here](https://github.com/kanaverse/scran.js-docker/pkgs/container/scran.js-docker%2Fbuilder), for easier use with PRs.
