### ISSUE TITLE
[JOSS] Instructions for getting unit tests to pass

### ISSUE THREAD

**Issue by yongrenjie** [kanaverse/scran.js#80]
(This issue is opened as part of @yongrenjie and @llewelld's review of the Journal of Open Source Software submission, [*'Powering single-cell analyses in the browser with WebAssembly'*](https://github.com/openjournals/joss-reviews/issues/5603).)

---

The [`developer_notes.md` file](https://github.com/kanaverse/scran.js/blob/master/docs/related/developer_notes.md) contains instructions for running unit tests:

```
# install dev dependencies
npm install --include=dev
npm run test
```

However, we were unable to get these tests to pass on our systems using these commands.

**Comment by LTLA** [comment]
Was there a specific error message? 

Node seems to change its Wasm-related flags semi-frequently (e.g., #70). It's kind of hard to predict which ones work for any given major version of Node. Hopefully some of these things will get out of "experimental" and become the default.

In any case, I added a mention of the [Docker image](https://github.com/kanaverse/scran.js-docker/pkgs/container/scran.js-docker%2Fbuilder) to the developer notes, which should solve the immediate issue.

**Comment by llewelld** [comment]
Thanks for looking at our comments (@yongrenjie and I are looking at this together). We tried it both with and without using the Dockerfile and got different errors in both cases.

Using the Dockerfile, initially building the image failed with the output show in the attached log output. We added `npm` to the dependencies to fix this (see PR #82).

[scran-js-docker.txt](https://github.com/kanaverse/scran.js/files/12114536/scran-js-docker.txt)  

After this the image builds, but then running the tests gives the errors shown in this second log output. Hopefully this will help with diagnosing.

[scran-js-tests.txt](https://github.com/kanaverse/scran.js/files/12114785/scran-js-tests.txt)

**Comment by LTLA** [comment]
Okay, there's quite a bit going on here.

The first is that we're in the middle of updating to **scran.js** 3.0.0, so you caught us right as I merged #81. It seems that you used the old Dockerfile with a newer version of the **scran.js** package that relies on the updated Emscripten SDK, which explains at least a few of the errors.

As part of the update, I moved the `Dockerfile` to a [separate repository](https://github.com/kanaverse/scran.js-docker) to provide more flexibility at supporting changes in the version of the toolchain. The Docker image is now hosted [here](https://github.com/kanaverse/scran.js-docker/pkgs/container/scran.js-docker%2Fbuilder); if you pull it and do:

```sh
# See comments in https://github.com/kanaverse/scran.js-docker#README.md
NODEBIN=$(echo /emsdk/node/*/bin)
export PATH="${NODEBIN}:${PATH}"

# Running the tests
cd /scran.js
npm run test
```

The tests should run fine.

**Comment by llewelld** [comment]
Thanks for this. It looks like the path (and therefore using the wrong `npm`) was the main problem I was experiencing as the same thing happened with earlier versions too. The additional path commands fix it.
```
Test Suites: 2 skipped, 42 passed, 42 of 44 total
Tests:       12 skipped, 149 passed, 161 total
Snapshots:   0 total
Time:        20.076 s
Ran all test suites.
```
So this is great; along with the link you've added to the Docker repo, that now provides a clear path to getting the tests to pass.

Please feel free to close this issue.

**Comment by yongrenjie** [comment]
Following the instructions in [`developer_notes.md`](https://github.com/kanaverse/scran.js/blob/master/docs/related/developer_notes.md) we've managed to get the tests working both locally and on Docker, so I think this can be closed!
